"""update_hash_field_to_key_hash

Revision ID: 0824caa4e79c
Revises: 71bb2a3fb0d0
Create Date: 2026-07-05 15:34:01.070502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0824caa4e79c'
down_revision: Union[str, Sequence[str], None] = '71bb2a3fb0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_hash', sa.VARCHAR(length=64), nullable=False))
    op.drop_constraint(op.f('api_keys_hash_key'), 'api_keys', type_='unique')
    op.create_unique_constraint(None, 'api_keys', ['key_hash'])
    op.drop_column('api_keys', 'hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.create_unique_constraint(op.f('api_keys_hash_key'), 'api_keys', ['hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_keys', 'key_hash')
    # ### end Alembic commands ###
