"""add_safe_display_opts_for_api_key

Revision ID: 71bb2a3fb0d0
Revises: 86df2c69661d
Create Date: 2026-07-05 01:13:36.645610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bb2a3fb0d0'
down_revision: Union[str, Sequence[str], None] = '86df2c69661d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.TEXT(), nullable=False))
    op.add_column('api_keys', sa.Column('masked_key', sa.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'masked_key')
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
