"""add_unique_constraint_on_active_machine_name

Revision ID: 86df2c69661d
Revises: e3bc2fa0f20b
Create Date: 2026-07-04 19:17:21.754578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86df2c69661d'
down_revision: Union[str, Sequence[str], None] = 'e3bc2fa0f20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_machines_name_unique_active', 'machines', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_machines_name_unique_active', table_name='machines', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
