"""add_machine_api_key_and_telemetry_models

Revision ID: e3bc2fa0f20b
Revises:
Create Date: 2026-07-04 16:59:39.908347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3bc2fa0f20b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('(is_active = true AND deleted_at IS NULL) OR (is_active = false AND deleted_at IS NOT NULL)', name='chk_deleted_at'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='apikey_status_enum'), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(status = 'REVOKED' AND revoked_at IS NOT NULL) OR (status = 'ACTIVE' AND revoked_at IS NULL)", name='chk_revoked_at'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('raw_telemetry',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('cpu_r', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('mem_u', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('mem_u_e', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('disk_u', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('disk_wa', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('load_1', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('disk_r', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('disk_w', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('disk_rb', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('eth1_pi', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('tcp_use', sa.INTEGER(), nullable=False),
    sa.Column('tcp_tw', sa.INTEGER(), nullable=False),
    sa.Column('retransegs', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('tcp_timeouts', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('out_rsts', sa.DOUBLE_PRECISION(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('time', 'machine_id')
    )
    op.create_table('telemetry_analysis',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_score', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('is_anomaly', sa.BOOLEAN(), nullable=False),
    sa.Column('model_version', sa.TEXT(), nullable=False),
    sa.Column('window_size_s', sa.INTEGER(), nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('time', 'machine_id')
    )
    # ### end Alembic commands ###

    # Manually added commands to create Timescaledb hypertables
    op.execute("SELECT create_hypertable('raw_telemetry', 'time');")
    op.execute("SELECT create_hypertable('telemetry_analysis', 'time');")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_analysis')
    op.drop_table('raw_telemetry')
    op.drop_table('api_keys')
    op.drop_table('machines')
    # ### end Alembic commands ###
    op.execute("DROP TYPE apikey_status_enum;")
